import { Inter } from "next/font/google";
import "../globals.css";
import "react-toastify/dist/ReactToastify.css";
import Sidebar from "../../components/shared/navigation/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex">
          <Sidebar />
          <div className="grow basis-full">{children}</div>
        </main>
      </body>
    </html>
  );
}
